### ISSUE TITLE
Missing dependency for Give Them Kell

### ISSUE THREAD

**Issue by michaelin** [bloodydoves/BattleTech-Advanced#82]
Hi,

The "Give Them Kell" mod doesn't load for me, due to missing dependencies. Manually adding [The Archer](https://www.nexusmods.com/battletech/mods/370) mod version 1.6.2.1 from Nexus resolved the issue.

Also note that the Give Them Kell readme states that it requires Flashpoint. Consider moving it to the Flashpoint Full Module.

OS: MacOS 10.14.4 Mohave
BTA version: 3.1.2 (BattleTech Advanced 3062 Core-452-v3-1-2-1570816051.zip)
DLC: Flashpoint + Urban Warfare

Installed by following [The Drop Dead Simple Guide to Installing BTML & ModTek & ModTek mods](https://github.com/BattleTechModders/ModTek/wiki/The-Drop-Dead-Simple-Guide-to-Installing-BTML-&-ModTek-&-ModTek-mods)

**Comment by bloodydoves** [comment]
Give them Kell requires BD_Archer, which is a CAB model. You did not install the Community Asset Bundle correctly, which is why the Archer from Nexus solved it: because that's the same "mod" that is in the CAB. Also, that Archer is depreciated and will not work on Battletech 1.7.1, don't use it. Further, this is not where I generally deal with technical issues. Please come to the Discord server in the future for technical support.

As for it moving to the Flashpoint Module, an interesting idea. I'll consider it. Thanks for the suggestion.

**Comment by michaelin** [comment]
You're right. I've removed the manually installed Archer and installed the Community Asset Bundle, which fixed the issue.
